#!/usr/bin/env Rscript
# this is the RScript to create figure 1A

x <-  c(1,2,3,4,5)
y <- c(5,4,3,2,1)
png("stairs.png")
barplot(x, y, xlab = "stairs")
dev.off()

# just trying to see if I can edit here and follow different versions even from the master branch
